default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: restaurants_ajaxified_development
test:
  <<: *default
  database: restaurants_ajaxified_test
